In [1]:
using LinearAlgebra
using Statistics

In [18]:
x = 3.0
y = 2.0

2.0

In [19]:
@show x + y
@show x .* y
@show x / y
@show x .^ y

x + y = 5.0
x .* y = 6.0
x / y = 1.5
x .^ y = 9.0


9.0

In [42]:
a =Vector(0:3)

4-element Vector{Int64}:
 0
 1
 2
 3

In [43]:
A = copy(reshape(Vector(0:19), (4,5))')

5×4 Matrix{Int64}:
  0   1   2   3
  4   5   6   7
  8   9  10  11
 12  13  14  15
 16  17  18  19

In [44]:
At = transpose(A)

4×5 transpose(::Matrix{Int64}) with eltype Int64:
 0  4   8  12  16
 1  5   9  13  17
 2  6  10  14  18
 3  7  11  15  19

In [32]:
B = [1 2 3; 2 0 4; 3 4 5]

3×3 Matrix{Int64}:
 1  2  3
 2  0  4
 3  4  5

In [33]:
Bt = transpose(B)

3×3 transpose(::Matrix{Int64}) with eltype Int64:
 1  2  3
 2  0  4
 3  4  5

In [36]:
Bt .== B # 1 == true

3×3 BitMatrix:
 1  1  1
 1  1  1
 1  1  1

### How permutedims() works

if we look at reshape(Array, dims=(1.rows,2.cols,...)), we can reshape by 1. rows, 2. cols, 3. sheets.

permutedims(Array, dims=(new_first_dim, new_sec_dim, ...)) indexes the old dimensions and lets one rearrange them. 

For example

```julia
a = reshape(Vector(0:23), (4, 3, 2)) # creates a Matrix with (dim=1) 3 rows, (dim=2) 4 cols, (dim=3) 2 sheets
permutedims(a, (2, 1, 3)) #formerly dim=2 becomes dim=1, dim=1 becomes dim=2, dim=3 stays the same
permutedims(a, (3, 1, 2)) # formerly dim=3 becomes dim=1, dim=1 becomes dim=2, dim=2 becomes dim=3
``` 

In [97]:
X = reshape(Vector(0:23), (4, 3, 2))
X2 = permutedims(X, (2, 1, 3))

3×4×2 Array{Int64, 3}:
[:, :, 1] =
 0  1   2   3
 4  5   6   7
 8  9  10  11

[:, :, 2] =
 12  13  14  15
 16  17  18  19
 20  21  22  23

In [2]:
C = permutedims(reshape(Vector(0:19), (4,5)), (2,1))
D = deepcopy(C)
E = C .+ D

5×4 Matrix{Int64}:
  0   2   4   6
  8  10  12  14
 16  18  20  22
 24  26  28  30
 32  34  36  38

In [3]:
F = C .* D # Hadamard product (C⊙ D) resulting from element-wise multiplication of both matrices

5×4 Matrix{Int64}:
   0    1    4    9
  16   25   36   49
  64   81  100  121
 144  169  196  225
 256  289  324  361

In [4]:
b = 2
G = permutedims(reshape(Vector(0:23), (4, 3, 2)), (2, 1, 3))

H = b .+ G
size(b.*G)

(3, 4, 2)

In [6]:
@show c = Vector(0:3)
sum(c)

c = Vector(0:3) = [0, 1, 2, 3]


6

In [115]:
@show size(C)
sum(C)

size(C) = (5, 4)


190

In [5]:
C_sum_dim_1 = sum(C, dims=1)

1×4 Matrix{Int64}:
 40  45  50  55

In [6]:
C_sum_dim_2 = sum(C, dims=2)

5×1 Matrix{Int64}:
  6
 22
 38
 54
 70

In [140]:
I = mean(C)

9.5

In [141]:
J = mean(C, dims=1)

1×4 Matrix{Float64}:
 8.0  9.0  10.0  11.0

In [7]:
K = C ./ C_sum_dim_2

5×4 Matrix{Float64}:
 0.0       0.166667  0.333333  0.5
 0.181818  0.227273  0.272727  0.318182
 0.210526  0.236842  0.263158  0.289474
 0.222222  0.240741  0.259259  0.277778
 0.228571  0.242857  0.257143  0.271429

In [131]:
L = cumsum(C, dims=1)

5×4 Matrix{Int64}:
  0   1   2   3
  4   6   8  10
 12  15  18  21
 24  28  32  36
 40  45  50  55

Usefulness of dot product: Dive into Deep Learning p. 61

In [33]:
g, h = ones(Int64,4), [0:3;]

([1, 1, 1, 1], [0, 1, 2, 3])

In [43]:
i = dot(g,h)

6

#### No need for broadcasting -- why?

In [44]:
Ch = C * h

5-element Vector{Int64}:
  14
  38
  62
  86
 110

In [13]:
C

5×4 Matrix{Int64}:
  0   1   2   3
  4   5   6   7
  8   9  10  11
 12  13  14  15
 16  17  18  19

### Matrix multiplication

Multiplication of two matrices **A** and **B** are possible, if the number of columns of matrix A are equal to the number of rows of matrix B. A(m, **n**) == B(**n**, q). This results in a matrix C which contains the number of rows from matrix A and the number of columns from matrix B. A(m,n) * B(n,q) = ***C(m, q)***. 

##### Rules: 

(A + B) * C = A * C + B * C  
r(A * B) = (rA) * B  
***A * B != B * A***

In [57]:
L = ones(4,3)
CL = (C * L)


5×3 Matrix{Float64}:
  6.0   6.0   6.0
 22.0  22.0  22.0
 38.0  38.0  38.0
 54.0  54.0  54.0
 70.0  70.0  70.0

### Norms

A norm is a function f() that maps a vector to a scalar.
r = scalar
x = Vector
```julia
(1) f(rx) = r * f(x)
(2) f(x + y) <= f(x) + f(y)
(3) f(x) >= 0
(4) [x] = 0 == f(x) = 0

L2-norm (aka Euclidean distance): x = sqrt(sum(x ^ 2)) ===> norm(x, 2) # norm(x, 2) is the default

L1-norm: norm(x, 1) or x = sum(abs.(x))
```

In [46]:
u = [3, -4]
norm(u)

5.0

In [58]:
norm(u, 1)

7.0

In [55]:
v = ones(4,9)
norm(v)

6.0