In [3]:
x = Int64[0:11;]

12-element Vector{Int64}:
  0
  1
  2
  3
  4
  5
  6
  7
  8
  9
 10
 11

In [4]:
size(x)

(12,)

In [5]:
axes(x)

(Base.OneTo(12),)

In [6]:
X = copy(reshape(x, (4,3))')


3×4 Matrix{Int64}:
 0  1   2   3
 4  5   6   7
 8  9  10  11

In [56]:
# zeros(rows, cols, dims)
z = zeros(3,4,2)

3×4×2 Array{Float64, 3}:
[:, :, 1] =
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0

[:, :, 2] =
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0

In [61]:
o = ones(3,4,2)

3×4×2 Array{Float64, 3}:
[:, :, 1] =
 1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0

[:, :, 2] =
 1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0

In [73]:
using Distributions
n = Normal(0, 1)
r = rand(n, (3,4))

3×4 Matrix{Float64}:
  0.312994  -0.992285   0.988426  -1.25722
 -0.442391  -1.10704   -0.697243  -1.9103
 -2.06282    0.816855   0.854017   0.81759

In [102]:
A = [2 1 4 3; 1 2 3 4; 4 3 2 1]

3×4 Matrix{Int64}:
 2  1  4  3
 1  2  3  4
 4  3  2  1

### Element-wise operation

Note that every element-wise operation has to include the "dot"-notation.

In [82]:
x = [1, 2, 4, 8]
y = [2, 2, 2, 2]

@show x .+ y
@show x .- y
@show x .* y
@show x ./ y # standard output-type is Float64
@show x .^ y

x .+ y = [3, 4, 6, 10]
x .- y = [-1, 0, 2, 6]
x .* y = [2, 4, 8, 16]
x ./ y = [0.5, 1.0, 2.0, 4.0]
x .^ y = [1, 4, 16, 64]


4-element Vector{Int64}:
  1
  4
 16
 64

In [213]:
Xx = copy(reshape(Vector(0:11), (4,3))')
Yy = [2 1 4 3; 1 2 3 4; 4 3 2 1]

X1 = vcat(Xx, Yy) # vertical concat, stacking matrices on top of each other 
X2 = hcat(Xx, Yy) # horizontal concat, stacking matrices next to each other, from left -> right

3×8 Matrix{Int64}:
 0  1   2   3  2  1  4  3
 4  5   6   7  1  2  3  4
 8  9  10  11  4  3  2  1

In [164]:
Xx .== Yy # dot-notation again because of element-wise operation!
          # note that this creates a BitMatrix, basically consisting of true and false values

3×4 BitMatrix:
 0  1  0  1
 0  0  0  0
 0  0  0  0

In [147]:
sum(Xx)

66

In [160]:
a = Vector(0:2)
b = copy(transpose(Vector(0:1)))

a .+ b

3×2 Matrix{Int64}:
 0  1
 1  2
 2  3

In [184]:
Xx[end, : ] # last row, all columns
Xx[2:3, : ] # 2 & 3 row, all columns

2×4 Matrix{Int64}:
 4  5   6   7
 8  9  10  11

In [215]:
Xx1 = deepcopy(Xx)
Xx1[2,3] = 9
Xx1

3×4 Matrix{Int64}:
 0  1   2   3
 4  5   9   7
 8  9  10  11